### ACCOUNT ADMINISTRATION FOR ADMINS

### SIGNUP
POST /idp-api/auth/signup HTTP/1.1
Host: localhost:3001
Content-Type: application/json

{
    "username": "kelvin",
    "email": "admin@test.com",
    "password": "test1234",
    "name": "test"
}

### SIGNIN
POST /idp-api/auth/local/signin HTTP/1.1
Host: localhost:3001
Content-Type: application/json

{
    "username": "test",
    "password": "test1234"
}